# Generated by Django 3.1.2 on 2020-10-12 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUser',
            fields=[
                ('about_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('interest_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=45)),
                ('proficiency', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Motivation',
            fields=[
                ('interest_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('technology_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TechSkills',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('vacancy_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
                ('company', models.CharField(max_length=45)),
                ('company_url', models.URLField()),
                ('category', models.CharField(max_length=45)),
                ('location_required', models.CharField(max_length=45)),
                ('requirements', models.TextField()),
                ('salary', models.FloatField()),
                ('description', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=100)),
                ('country', models.CharField(default='', max_length=45)),
                ('city', models.CharField(blank=True, default='', max_length=45)),
                ('phone_number', models.CharField(default='', max_length=45)),
                ('birthday', models.DateTimeField()),
                ('summary', models.CharField(default='', max_length=250)),
                ('linkedin_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('about', models.ManyToManyField(blank=True, related_name='users', to='hovify_app.AboutUser')),
                ('interests', models.ManyToManyField(blank=True, related_name='users', to='hovify_app.Interest')),
                ('languages', models.ManyToManyField(blank=True, related_name='users', to='hovify_app.Language')),
                ('motivations', models.ManyToManyField(blank=True, related_name='users', to='hovify_app.Motivation')),
                ('tech_skills', models.ManyToManyField(blank=True, related_name='users', to='hovify_app.TechSkills')),
                ('vacancies', models.ManyToManyField(blank=True, related_name='users', to='hovify_app.Vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=45)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('project_url', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hovify_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('professional_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=45)),
                ('role', models.CharField(max_length=100)),
                ('initial_date', models.DateTimeField()),
                ('final_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hovify_app.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hovify_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hovify_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('edu_id', models.AutoField(primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('initial_date', models.DateTimeField()),
                ('final_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hovify_app.user')),
            ],
        ),
    ]
