# Generated by Django 2.1 on 2020-10-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hovify_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Password',
        ),
    ]
