# Generated by Django 2.1 on 2020-10-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hovify_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='cover_letter',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='csv_data',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='pdf_path',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='preview_path',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
