# Generated by Django 2.1 on 2020-10-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hovify_app', '0002_auto_20201023_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Location',
            field=models.CharField(blank=True, default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='PhoneNumber',
            field=models.CharField(blank=True, default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Summary',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
