# Generated by Django 2.1 on 2020-10-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hovify_app', '0002_auto_20201019_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='GitHubURL',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='LinkedIn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='PortfolioURL',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='TwitterURL',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
