# Generated by Django 2.1 on 2020-10-23 05:44

from django.db import migrations, models
import django.db.models.deletion
import hovify.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('hovify_app', '0003_auto_20201023_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='cover_letter',
            field=models.FileField(blank=True, storage=hovify.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='csv_data',
            field=models.FileField(blank=True, storage=hovify.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='pdf_path',
            field=models.FileField(blank=True, storage=hovify.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='preview_path',
            field=models.FileField(blank=True, storage=hovify.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='userID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hovify_app.Profile'),
        ),
    ]
