# Generated by Django 2.1 on 2020-10-23 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hovify_app', '0004_auto_20201023_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='userID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
